development:
  adapter: postgresql
  encoding: unicode
  database: example_development
  pool: 5
  username: example_username
  password: example_password

test:
  adapter: postgresql
  encoding: unicode
  database: example_test
  pool: 5
  username: example_username
  password: example_password