development:
  adapter: postgresql
  encoding: unicode
  database: hiphoplog_development
  pool: 5
  username: cmakoumbou
  password: mabika

test:
  adapter: postgresql
  encoding: unicode
  database: hiphoplog_test
  pool: 5
  username: cmakoumbou
  password: mabika

production:
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>